language: generic

services:
  - docker

before_install:
  - docker build -t sdk-generator .
  - CID=`docker run -d -ti --rm sdk-generator:latest`
  - docker cp $CID:/opt/node-sdk/sdk ./sdk
  - docker kill $CID

script:
  - git config user.email tech.api.team@shutterstock.com
  - git config user.name shutterbot
  - git clone https://$GH_USER:$GH_PASS@github.com/shutterstock/public-api-javascript-sdk.git
  - cp -r ./sdk/src ./public-api-javascript-sdk
  - cp ./sdk/package.json ./public-api-javascript-sdk
  - cd ./public-api-javascript-sdk
  - echo "node_modules" > .gitignore
  - nvm install 10
  - nvm use 10
  - yarn add --dev chai
  - git add .
  - git commit -m "Updating JavaScript SDK"
  - git push
